version: '3'

services:
  firebase:
    build: .
    container_name: firebase-templete
    ports:
      - 4000:4000 # Emulator Suite UI
      - 5000:5000 # Firebase Hosting
      - 5001:5001 # Clound Functions
      - 8080:8080 # Cloud Firestore
      - 9005:9005
      - 9099:9099 # auth emulator
      - 9199:9199 # storage emulator
#      - 8085:8085 # Cloud Pub/Sub
#      - 9000:9000 # Realtime Database
    volumes:
      - ./firebase/emulators/:/app:cached
      - ./firebase/bin/:/root/.cache:cached
      - ./firebase/config/:/root/.config:cached
      - ./app:/app
    working_dir: /app
    tty: true
    stdin_open: true
    command: /bin/bash