version: '3'
services:
  python:
    build:
      context: ./docker/python
    volumes:
      - ./server:/var/www/server
    tty: true
    ports:
      - "127.0.0.1:8080:80"
    environment:
      FLASK_ENV: development
    command: sh -c "python main.py"
  node:
    build: 
      context: ./docker/nodejs
    volumes:
      - ./web:/var/www
    tty: true
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      HOST: 0.0.0.0
    command: sh -c "yarn install && yarn dev"