on:
  push:
    branches:
      - env/prod

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      
      - name: cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: nuxt setup
        run: echo "${{ secrets.PROD_ENV }}" > .env
        working-directory: ./web
        
      - name: nuxt generate
        run: |
          yarn
          yarn generate
        working-directory: ./web
      
      - name: copy files
        run: |
          rm -rf app/dist
          cp -r web/dist app
        working-directory: ./
      
      - name: firebase setup
        run: |
          npm install -g firebase-tools
          npm install
        working-directory: ./app/functions
      
      - name: firebase deploy
        run: |
          firebase deploy --project d-shrine --token=${{ secrets.FIREBASE_TOKEN }}
        working-directory: ./app
        

